### PR TITLE
Move CI to GitHub Actions

### PR DESCRIPTION
**Pull request by giordano**
@ajkeller34 could you please add a [`DOCUMENTER_KEY`](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh) for GitHub Actions?  And also delete the webhook of AppVeyor from the settings.  Thanks!

### CODE REVIEW

**Comment by giordano** [comment]
@ajkeller34 ping :slightly_smiling_face:

**Comment by ajkeller34** [comment]
Thank you for the reminder. Hopefully this works!

**Comment by giordano** [comment]
@ajkeller34 thanks!  Could you please remove the AppVeyor webhook?  Otherwise all jobs will have a red cross because AppVeyor isn't smart enough to understand it doesn't have to run if there is no script :facepalm:

**Comment by ajkeller34** [comment]
Ok, I deleted the AppVeyor webhook.

**Comment by giordano** [comment]
Ok, thanks!

**Pull request merged**
