### PR TITLE
Allow for array division by unit

### PR DESCRIPTION
**Pull request by briochemc**
This PR adds a `/(Array, Unit)` method. I sometimes find myself doing things like

```julia
using Unitful: m, s
[1, 2, 3] * m/s
```

but Unitful.jl v1.3.0 throws because there is no such method.

### CODE REVIEW

**Comment by briochemc** [comment]
@ajkeller34 Could you take a look at these? (not sure who else to ping to get PRs merged quicker 😄)

**Comment by briochemc** [comment]
Thanks, @giordano! 🙏  Care to make a release?

**Comment by giordano** [comment]
> Care to make a release?

To facilitate a new release, you're better off bumping the version number as appropriate directly in the PR where you propose the change :wink:

**Comment by briochemc** [comment]
Ha yes I forgot!

**Pull request merged**
